---

uiStyle:
  button:
    normal: { img: ui/ui_button.png, colour: "#9C5BB5" }
    down: { img: ui/ui_button.png, colour: "#913DA3" }
    hover: { img: ui/ui_button.png, colour: "#B68FCB" }
    innerBorder: [ 5, 5, 5, 5 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }

  input:
    box: { img: ui/ui_input.png, colour: "#9861B6" }
    innerBorder: [ 6, 5, 6, 2 ]
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    labelGhost: { font: Ubuntu Bold, size: 18, colour: "#7F7F7F" }

  list:
    background: ""
    item:
      normal: { img: ui/ui_list_item.png, colour: "#9C5BB5" }
      hover: { img: ui/ui_list_item.png, colour: "#B68FCB" }
      selected: { img: ui/ui_list_item.png, colour: "#913DA3" }
      innerBorder: [ 6, 5, 6, 2 ]
    innerBorder: [ 0, 0, 0, 0 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    selectionChangedSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFFCF" }
    selectedLabel: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    gap: 1

  scrollbar:
    bar.normal: { img: ui/ui_scrollbar.png, colour: "#5E3962" }
    up:
      normal: { img: ui/ui_scrollbar.png, colour: "#9C5BB5" }
      disabled: { img: ui/ui_scrollbar.png, colour: "#8D7B95" }
      down: { img: ui/ui_scrollbar.png, colour: "#913DA3" }
      hover: { img: ui/ui_scrollbar.png, colour: "#B68FCB" }
      innerBorder: [ 3, 3, 3, 3 ]
      upSound: ""
      downSound: ""
      hoverSound: ""
    down:
      normal: { img: ui/ui_scrollbar.png, colour: "#9C5BB5" }
      disabled: { img: ui/ui_scrollbar.png, colour: "#8D7B95" }
      down: { img: ui/ui_scrollbar.png, colour: "#913DA3" }
      hover: { img: ui/ui_scrollbar.png, colour: "#B68FCB" }
      innerBorder: [ 3, 3, 3, 3 ]
      upSound: ""
      downSound: ""
      hoverSound: ""
    thumb:
      normal: { img: ui/ui_scrollbar.png, colour: "#9C5BB5" }
      down: { img: ui/ui_scrollbar.png, colour: "#913DA3" }
      hover: { img: ui/ui_scrollbar.png, colour: "#B68FCB" }
      innerBorder: [ 3, 3, 3, 3 ]
      upSound: ""
      downSound: ""
      hoverSound: ""

  label:
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }

...