---

uiStyle:
  toolbar:
    background: ""
    item:
      selected: { img: ui/slant_capsule.png, colour: "#FFFFFF", imageColour: "#000000" }
      hover: { img: ui/slant_capsule.png, colour: "#F98A9A" }
      normal: { img: ui/slant_capsule.png, colour: "#FC2847" }
      innerBorder: [ 8, 5, 8, 2 ]
    innerBorder: [ 0, 0, 0, 0 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    selectionChangedSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFFCF" }
    selectedLabel: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    selectedImageColour: '#000000'
    gap: -5

  flatButton:
    normal: { img: whitebox.png, colour: "#00000000" }
    down: { img: whitebox.png, colour: "#00000000" }
    hover: { img: whitebox.png, colour: "#00000000" }
    innerBorder: [ 0, 0, 0, 0 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    labelBorder: [0, 0, 0, 0]
    iconBorder: [0, 0, 0, 0]
    hoveredIconColour: "#FFCDCD"

  labelLight:
    label: { font: Ubuntu Light, size: 14, colour: "#FFFFFF" }

  inputThin:
    box: { img: halley_ui/ui_input_thin.png, colour: "#9861B6" }
    caret: halley_ui/ui_caret.png
    innerBorder: [ 6, 3, 6, 2 ]
    label: { font: Ubuntu Light, size: 14, colour: "#FFFFFF" }
    labelGhost: { font: Ubuntu Light, size: 14, colour: "#7F7F7F" }

  buttonThin:
    normal: { img: halley_ui/ui_button.png, colour: "#9C5BB5" }
    down: { img: halley_ui/ui_button.png, colour: "#913DA3" }
    hover: { img: halley_ui/ui_button.png, colour: "#B68FCB" }
    disabled: { img: halley_ui/ui_button.png, colour: "#927B95" }
    innerBorder: [ 5, 0, 5, 1 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 14, colour: "#FFFFFF" }
    labelBorder: [0, 0, 0, 0]
...