---

uiStyle:
  toolbar:
    background: ""
    item:
      selected: { img: ui/slant_capsule.png, colour: "#FFFFFF", imageColour: "#000000" }
      hover: { img: ui/slant_capsule.png, colour: "#F98A9A" }
      normal: { img: ui/slant_capsule.png, colour: "#FC2847" }
      innerBorder: [ 8, 1, 8, 1 ]
    innerBorder: [ 0, 0, 0, 0 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    selectionChangedSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFFCF" }
    selectedLabel: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    selectedImageColour: '#000000'
    gap: -5

  flatButton:
    normal: { img: whitebox.png, colour: "#00000000" }
    down: { img: whitebox.png, colour: "#00000000" }
    hover: { img: whitebox.png, colour: "#00000000" }
    innerBorder: [ 0, 0, 0, 0 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    labelBorder: [0, 0, 0, 0]
    iconBorder: [0, 0, 0, 0]
    hoveredIconColour: "#FFCDCD"

  slantButton:
    selected: { img: ui/slant_capsule.png, colour: "#FFFFFF", imageColour: "#000000" }
    hover: { img: ui/slant_capsule.png, colour: "#F98A9A" }
    normal: { img: ui/slant_capsule.png, colour: "#FC2847" }
    down: { img: ui/slant_capsule.png, colour: "#D30322" }
    innerBorder: [ 15, 0, 15, 0 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 18, colour: "#FFFFFF" }
    labelBorder: [0, 0, 0, 0]
    iconBorder: [0, 0, 0, 0]
    hoveredIconColour: "#FFCDCD"

...