name: Default
base: colour_schemes/base_dark
colours:
  ui_controlNormal: "#40424D"
  ui_controlDown: "#30323A"
  ui_controlHover: "#6D7285"
  ui_controlDisabled: "#191919"

  ui_buttonNormal: "#3C4051"
  ui_buttonDown: "#2D303E"
  ui_buttonHover: "#656D8D"
  ui_buttonDisabled: "#191919"

  ui_listBackground: "#25262E"
  ui_listSelected: "#9A4E5B"
  ui_listHover: "#4A2F38"
  ui_listDrag: "#40424D80"

  ui_inputBox: "#86838D"

  ui_scrollBackground: "#212227"
  ui_backgroundBox: "#1E1E1E"
  ui_popupWindow: "#53131F"
  ui_staticBox: "#40424D"
  ui_staticBoxSubdue: "#30323A"

  ui_debugConsole: "#1E1E1EC0"
