name: Dark Glass
base: colour_schemes/base_dark
colours:
  ui_controlNormal: "#40424D"
  ui_controlDown: "#30323A"
  ui_controlHover: "#6D7285"
  ui_controlDisabled: "#191919"

  ui_buttonNormal: "#3C4051"
  ui_buttonDown: "#2D303E"
  ui_buttonHover: "#656D8D"
  ui_buttonDisabled: "#191919"

  ui_inputNormal: "#86838D"
  ui_inputDown: "#726F79"
  ui_inputHover: "#A29FA8"
  ui_inputDisabled: "#363636"

  ui_listBackground: "#25262E80"
  ui_listSelected: "#9A4E5B"
  ui_listHover: "#4A2F38"
  ui_listDrag: "#40424D80"

  ui_scrollBackground: "#212227D0"
  ui_backgroundBox: "#1E1E1E80"
  ui_popupWindow: "#53131FD0"
  ui_popupWindowSolid: "#53131F"
  ui_staticBox: "#40424DD0"
  ui_staticBoxSubdue: "#30323AD0"

  ui_debugConsole: "#1E1E1EC0"
