name: Sakura
base: colour_schemes/base_light
colours:
  background0: "#FFECF7"
  background1: "#FFF0F9"
  backgroundLogo: "#FFE8F5"

  ui_controlNormal: "#F493AD"
  ui_controlDown: "#C4395C"
  ui_controlHover: "#F9BFCF"
  ui_controlDisabled: "#D7AAB6"
  
  ui_buttonNormal: "#FFC6E7"
  ui_buttonDown: "#E281C0"
  ui_buttonHover: "#FFD9EF"
  ui_buttonDisabled: "#D7AAB6"

  ui_inputNormal: "#F493AD"
  ui_inputDown: "#C4395C"
  ui_inputHover: "#F9BFCF"
  ui_inputDisabled: "#D7AAB6"

  ui_listBackground: "#F4A4B7C0"
  ui_listSelected: "#FFFFFF"
  ui_listHover: "#FFC6E7"
  ui_listDrag: "#FFC6E780"

  ui_scrollBackground: "#F8E0EF"
  ui_backgroundBox: "#F8E0EF"
  ui_popupWindow: "#FFC6E7"
  ui_staticBox: "#FFC6E7"
  ui_staticBoxSubdue: "#F9ACD5"

  ui_debugConsole: "#FFCDDBC0"

  ui_selectedTextAlt: "#9C2E94"
  ui_unselectedTextAlt: "#9C2E94"

  ui_disabledText: "#C76D94"
  ui_disabledTextAlt: "#774077"

  ui_logWarningText: "#FFA626"

  scrollBackground: "#FFDDE6"

  taskbarLogoBackground: "#FFD7EE"

sprites:
  ui_button: { img: halley_ui/ui_button.png, material: "Halley/SpriteGradient", custom0: [1.0, 0.165, 0.08, 2.0] }

backgroundParticles:
  particles:
    spawnRate: 25
    angle: 135
    angleScatter: 25
    speed: 100
    acceleration: [-10, 10]
    ttl: 10
    fadeInTime: 1
    fadeOutTime: 1
    speedDamp: 0.2
    directionScatter: 150
    rotateTowardsMovement: true
  sprites:
  - { img: halley_ui/particles_sakura.png, colour: "#FFFFFF" }