---

uiStyle:
  button:
    normal: { img: $ui_button, colour: $ui_buttonNormal }
    down: { img: $ui_button, colour: $ui_buttonDown }
    hover: { img: $ui_button, colour: $ui_buttonHover }
    disabled: { img: $ui_button, colour: $ui_buttonDisabled }
    innerBorder: [ 5, 5, 5, 5 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 15, colour: $ui_text }
    disabledLabel: { font: Ubuntu Bold, size: 15, colour: $ui_disabledText }
    labelBorder: [0, 0, 0, 0]
    iconBorder: [0, 0, 0, 0]
    iconColour: $ui_text
    iconColourDisabled: $ui_disabledText

  buttonThin:
    normal: { img: $ui_button, colour: $ui_buttonNormal }
    down: { img: $ui_button, colour: $ui_buttonDown }
    hover: { img: $ui_button, colour: $ui_buttonHover }
    disabled: { img: $ui_button, colour: $ui_buttonDisabled }
    innerBorder: [ 5, 0, 5, 1 ]
    upSound: ""
    downSound: ""
    hoverSound: ""
    label: { font: Ubuntu Bold, size: 14, colour: $ui_text }
    disabledLabel: { font: Ubuntu Bold, size: 14, colour: $ui_disabledText }
    labelBorder: [0, 0, 0, 0]
    iconColour: $ui_text
    disabledIconColour: $ui_disabledText

  checkbox:
    normal: { img: $ui_checkbox, colour: $ui_inputNormal }
    checked: { img: $ui_checkbox_checked, colour: $ui_inputNormal }
    hover: { img: $ui_checkbox, colour: $ui_inputHover }
    checkedHover: { img: $ui_checkbox_checked, colour: $ui_inputHover }
    disabled: { img: $ui_checkbox, colour: $ui_inputDisabled }
    checkedDisabled: { img: $ui_checkbox_checked, colour: $ui_inputDisabled }

  input:
    box: { img: $ui_input_thin, colour: $ui_inputNormal }
    caret: { img: halley_ui/ui_caret.png, colour: $ui_inputCaret }
    innerBorder: [ 6, 2, 6, 1 ]
    label: { font: Ubuntu Regular, size: 15, colour: $ui_text }
    labelGhost: { font: Ubuntu Regular, size: 15, colour: $ui_textGhost }
    minSize: 22

  inputThin:
    box: { img: $ui_input_thin, colour: $ui_inputNormal }
    caret: { img: halley_ui/ui_caret.png, colour: $ui_inputCaret }
    innerBorder: [ 6, 2, 6, 3 ]
    label: { font: Ubuntu Light, size: 14, colour: $ui_text }
    labelGhost: { font: Ubuntu Light, size: 14, colour: $ui_textGhost }
    minSize: 22

  dropdown:
    normal: { img: $ui_dropdown_closed, colour: $ui_inputNormal }
    hover: { img: $ui_dropdown_closed, colour: $ui_inputHover }
    open: { img: $ui_dropdown_open, colour: $ui_inputHover }
    disabled: { img: $ui_dropdown_closed, colour: $ui_inputDisabled }
    background: { img: $ui_dropdown_window, colour: $ui_inputHover }
    innerBorder: [ 2, 2, 2, 2 ]
    labelBorder: [ 6, 2, 0, -4 ]
    label: { font: Ubuntu Regular, size: 15, colour: $ui_text }
    selectedLabel: { font: Ubuntu Regular, size: 15, colour: $ui_text }
    openSound: ""
    closeSound: ""
    height: 200
    minSize: 22
    iconGap: 4
    minSizeMargins: [ 40, 20, 0, 0 ]
    listStyle: list
    scrollbarStyle: scrollbar

  dropdownLight:
    normal: { img: $ui_dropdown_closed, colour: $ui_inputNormal }
    hover: { img: $ui_dropdown_closed, colour: $ui_inputHover }
    open: { img: $ui_dropdown_open, colour: $ui_inputHover }
    disabled: { img: $ui_dropdown_closed, colour: $ui_inputDisabled }
    background: { img: $ui_dropdown_window, colour: $ui_inputHover }
    innerBorder: [ 2, 2, 2, 2 ]
    labelBorder: [ 6, 2, 0, -4 ]
    label: { font: Ubuntu Light, size: 14, colour: $ui_text }
    selectedLabel: { font: Ubuntu Light, size: 14, colour: $ui_text }
    openSound: ""
    closeSound: ""
    height: 200
    minSize: 22
    iconGap: 4
    minSizeMargins: [ 40, 20, 0, 0 ]
    listStyle: listLight
    scrollbarStyle: scrollbar

  list:
    background: { img: "halley_ui/ui_list_item.png", colour: $ui_listBackground }
    item:
      normal: ""
      hover: { img: halley_ui/ui_list_item_selection.png, colour: $ui_listHover }
      selected: { img: halley_ui/ui_list_item_selection.png, colour: $ui_listSelected }
      drag: { img: halley_ui/ui_list_item.png, colour: $ui_listDrag }
      innerBorder: [ 6, 5, 6, 2 ]
    innerBorder: [ 0, 0, 0, 0 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    selectionChangedSound: ""
    label: { font: Ubuntu Regular, size: 15, colour: $ui_unselectedText }
    selectedLabel: { font: Ubuntu Regular, size: 15, colour: $ui_selectedText }
    gap: 1

  listLight:
    background: { img: "halley_ui/ui_list_item.png", colour: $ui_listBackground }
    item:
      normal: ""
      hover: { img: halley_ui/ui_list_item_selection.png, colour: $ui_listHover }
      selected: { img: halley_ui/ui_list_item_selection.png, colour: $ui_listSelected }
      drag: { img: halley_ui/ui_list_item.png, colour: $ui_listDrag }
      innerBorder: [ 6, 5, 6, 2 ]
    innerBorder: [ 0, 0, 0, 0 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    selectionChangedSound: ""
    label: { font: Ubuntu Light, size: 14, colour: $ui_unselectedText }
    selectedLabel: { font: Ubuntu Light, size: 14, colour: $ui_selectedText }
    gap: 1

  treeList:
    background: { img: "halley_ui/ui_list_item.png", colour: $ui_listBackground }
    item:
      normal: ""
      hover: { img: halley_ui/ui_list_item_selection.png, colour: $ui_listHover }
      selected: { img: halley_ui/ui_list_item_selection.png, colour: $ui_listSelected }
      drag: { img: halley_ui/ui_list_item.png, colour: $ui_listDrag }
      innerBorder: [ 0, 0, 0, 0 ]
    innerBorder: [ 0, 0, 0, 0 ]
    labelBorder: [ 6, 5, 6, 2 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    selectionChangedSound: ""
    label:
      normal: { font: Ubuntu Regular, size: 13, colour: $ui_unselectedText }
      selected: { font: Ubuntu Regular, size: 13, colour: $ui_selectedText }
      disabled: { font: Ubuntu Regular, size: 13, colour: $ui_disabledText }
    labelSpecial:
      normal: { font: Ubuntu Regular, size: 13, colour: $ui_unselectedTextAlt }
      selected: { font: Ubuntu Regular, size: 13, colour: $ui_selectedTextAlt }
      disabled: { font: Ubuntu Regular, size: 13, colour: $ui_disabledTextAlt }
    gap: 1
    indentation: 20
    cursor:
      beforeAfter: { img: "whitebox.png" }
      over: { img: "whitebox.png", colour: "#FFFFFF80" }
    controls:
      guide_i: { img: "halley_ui/ui_treeview_line_i.png", colour: $ui_controlNormal }
      guide_t: { img: "halley_ui/ui_treeview_line_t.png", colour: $ui_controlNormal }
      guide_l: { img: "halley_ui/ui_treeview_line_l.png", colour: $ui_controlNormal }
      guide_empty: { img: "halley_ui/ui_treeview_line_i.png", colour: "#00000000" }
      leaf: { img: "halley_ui/ui_treeview_leaf.png", colour: $ui_controlNormal }
      element: { img: "halley_ui/ui_treeview_element.png", colour: "#FFFFFF" }
      collapseButton:
        normal: { img: halley_ui/ui_treeview_expanded.png, colour: $ui_buttonNormal }
        down: { img: halley_ui/ui_treeview_expanded.png, colour: $ui_buttonDown }
        hover: { img: halley_ui/ui_treeview_expanded.png, colour: $ui_buttonHover }
        disabled: { img: halley_ui/ui_treeview_expanded.png, colour: $ui_buttonDisabled }
        innerBorder: [ 0, 0, 0, 0 ]
        upSound: ""
        downSound: ""
        hoverSound: ""
        label: { font: Ubuntu Regular, size: 13, colour: $ui_text }
        labelBorder: [0, 0, 0, 0]
      expandButton:
        normal: { img: halley_ui/ui_treeview_collapsed.png, colour: $ui_buttonNormal }
        down: { img: halley_ui/ui_treeview_collapsed.png, colour: $ui_buttonDown }
        hover: { img: halley_ui/ui_treeview_collapsed.png, colour: $ui_buttonHover }
        disabled: { img: halley_ui/ui_treeview_collapsed.png, colour: $ui_buttonDisabled }
        innerBorder: [ 0, 0, 0, 0 ]
        upSound: ""
        downSound: ""
        hoverSound: ""
        label: { font: Ubuntu Regular, size: 13, colour: $ui_text }
        labelBorder: [0, 0, 0, 0]

  scrollbar:
    bar:
      horizontal: { img: halley_ui/ui_scrollbar.png, colour: $ui_scrollBackground }
      vertical: { img: halley_ui/ui_scrollbar.png, colour: $ui_scrollBackground }
    thumb:
      normal: { img: halley_ui/ui_scrollbar.png, colour: $ui_controlNormal }
      down: { img: halley_ui/ui_scrollbar.png, colour: $ui_controlDown }
      hover: { img: halley_ui/ui_scrollbar.png, colour: $ui_controlHover }
      innerBorder: [ 3, 3, 3, 3 ]
      upSound: ""
      downSound: ""
      hoverSound: ""

  label:
    label: { font: Ubuntu Bold, size: 15, colour: $ui_text }

  labelToolbar:
    label: { font: Ubuntu Bold, size: 15, colour: $toolbarText }

  labelLight:
    label: { font: Ubuntu Light, size: 14, colour: $ui_text }

  labelSmall:
    label: { font: Ubuntu Light, size: 12, colour: $ui_text }

  labelSmallDisabled:
    label: { font: Ubuntu Light, size: 12, colour: $ui_disabledText }

  labelOutline:
    label: { font: Ubuntu Bold, size: 15, colour: $ui_text, outline: 2, outlineColour: $ui_text_outline }

  tooltip:
    background: { img: $ui_tooltip, colour: $ui_listHover }
    innerBorder: [ 5, 5, 5, 5 ]
    delay: 0.3
    maxWidth: 200
    label: { font: Ubuntu Bold, size: 14, colour: $ui_text }

  slider:
    emptyBar: { img: halley_ui/slider_bar_empty.png, colour: $ui_controlDisabled }
    fullBar: { img: halley_ui/slider_bar_full.png, colour: $ui_controlNormal }
    left: { img: halley_ui/slider_bar_left.png, colour: $ui_controlNormal }
    right: { img: halley_ui/slider_bar_right.png, colour: $ui_controlDisabled }
    thumb: { img: halley_ui/slider_thumb.png, colour: $ui_controlHover }
    labelBorder: { img: whitebox.png, colour: "#00000000" }
    innerBorder: [3, 0, 2, 0]
    barBorder: [0, 1, 6, 1]
    labelInnerBorder: [2, 0, 2, 0]
    extraMouseBorder: [1, 3, 1, 3]
    label: { font: Ubuntu Bold, size: 14, colour: $ui_text }

  tabs:
    background: { img: $ui_tabs_bg, colour: $ui_controlNormal }
    item:
      normal: { img: $ui_tab_normal, colour: $ui_controlNormal }
      hover: { img: $ui_tab_hover, colour: $ui_controlNormal }
      selected: { img: $ui_tab_selected, colour: $ui_controlNormal }
      disabled: { img: $ui_tab_normal, colour: $ui_controlNormal }
      innerBorder: [ 5, 6, 5, 2 ]
    innerBorder: [ 10, 0, 10, 0 ]
    extraMouseBorder: [ 0, 0, 0, 0 ]
    label: { font: Ubuntu Bold, size: 14, colour: $ui_unselectedText }
    selectedLabel: { font: Ubuntu Bold, size: 14, colour: $ui_selectedText }
    disabledLabel: { font: Ubuntu Bold, size: 14, colour: $ui_disabledText }
    selectionChangedSound: ""
    gap: 1

  scrollBackground:
    background: { img: $ui_scroll_background, colour: $scrollBackground }

  graphNode:
    paintBackground: { img: $ui_title_capsule, colour: $taskComplete }
    screenBackground: { img: $ui_title_capsule, colour: $taskRunning }
    outputBackground: { img: $ui_title_capsule, colour: $taskError }

  graphConnections:
    colourBuffer: $ui_logErrorText
    depthStencilBuffer: $ui_logDevText
    texture: $ui_logInfoText
...