---
widget: { id: capsule, class: image, image: "$ui_title_capsule", innerBorder: [ 4, 1, 4, 4 ], colour: $ui_staticBox }
sizer: { type: vertical }
children:
- sizer: { type: horizontal }
  children:
  - widget: { id: componentType, class: label, text: "Name" }
    fill: centre
    proportion: 1
  - widget: { id: copyComponentButton, class: button, icon: "entity_icons/copy_small.png", size: [20, 18], style: buttonThin, tooltip: "Copy Component to Clipboard" }
  - widget: { id: deleteComponentButton, class: button, text: "x", size: [20, 18], style: buttonThin, tooltip: "Delete Component" }
    border: [0, 0, -2, 0]
- widget: { id: componentFields, class: widget }
  border: [1, 4, 1, 1]
  sizer: { type: vertical, gap: 2 }
...