---
widget: { class: widget }
sizer: { type: vertical }
children:
- widget: { id: contents, class: scrollBarPane, scrollHorizontal: true, scrollVertical: true, mouseWheelEnabled: false }
  proportion: 1
  fill: fill
  sizer: { type: vertical }
  children:
  - widget: { class: scrollBackground, id: scrollBackground }
    proportion: 1
    children: []
...
