---

widget: { class: widget }
sizer: { type: vertical }
children:
- stretchSpacer: {}
  proportion: 1
- widget: { id: logo, class: image, image: "halley/halley_logo_dist.png" }
  border: [0, -50, 0, -50]
- stretchSpacer: {}
  proportion: 0.5
- widget: { class: image, image: $ui_float_window, innerBorder: [ 14, 11, 14, 14 ], colour: $ui_popupWindow }
  sizer: { type: vertical }
  children:
  - widget: { id: title, class: label, text: "Load Project" }
    fill: centre
  - widget: { id: topLabel, class: label, style: labelLight, text: "Enter the path of the project to load:" }
    border: [0, 5, 0, 0]
    fill: centre
  - widget: { class: scrollBarPane, size: [200, 250] }
    proportion: 1
    border: [0, 5, 0, 5]
    sizer: { type: vertical }
    children:
    - widget: { id: recent, class: list }
      proportion: 1
  - sizer: { type: horizontal }
    children:
    - widget: { id: input, class: textInput, size: [400, 22] }
      proportion: 1
    - widget: { id: ok, class: button, text: "OK", size: [60, 22], tooltip: "Load the selected Project" }
- stretchSpacer: {}
  proportion: 1

...