---

widget: { class: widget }
sizer: { type: horizontal, gap: 0 }
children:
- widget: { class: image, image: ui/slant_capsule_right_short.png, size: [40, 32], colour: "#FC2847" }
  border: [0, 3, -5, 3]
- widget: 
    id: toolbar
    class: list
    type: horizontal
    style: toolbar
    options:
    - id: assets
      image: ui/toolbar_assets.png
    - id: scene
      image: ui/toolbar_scene.png
    - id: ecs
      image: ui/toolbar_ecs.png
    - id: remote
      image: ui/toolbar_remote.png
    - id: properties
      image: ui/toolbar_properties.png
    - id: settings
      image: ui/toolbar_settings.png
- widget: { class: image, image: ui/slant_capsule_left_short.png, size: [20, 32], colour: "#FC2847" }
  border: [-5, 3, 0, 3]
- widget: { class: image, image: whitebox.png, size: [100, 32], colour: "#FC2847" }
  children:
  - widget: { class: label, id: toolName, text: Assets }
    fill: centre
    proportion: 1
  border: [0, 3, 0, 3]
- widget: { class: image, image: ui/slant_capsule_right_short.png, size: [20, 32], colour: "#FC2847" }
  border: [0, 3, 0, 3]
- stretchSpacer: {}
  proportion: 1
- widget: { class: image, image: ui/slant_capsule_left_short.png, size: [20, 32], colour: "#FC2847" }
  border: [0, 3, 0, 3]
- widget: { class: image, image: whitebox.png, size: [80, 32], colour: "#FC2847" }
  border: [0, 3, 0, 3]
  children:
  - widget: { class: label, id: gameName, text: Halley Game }
    fill: centre
    proportion: 1
    border: [0, 0, 0, 0]
- widget: { class: image, image: ui/slant_capsule_right_short.png, size: [20, 32], colour: "#FC2847" }
  border: [0, 3, 0, 3]
- widget: { class: image, image: ui/slant_capsule_left_short.png, size: [20, 32], colour: "#FC2847" }
  border: [-4, 3, 0, 3]
- widget: { class: image, image: whitebox.png, size: [20, 32], colour: "#FC2847" }
  border: [0, 3, 0, 3]
  children:
  - widget: { id: exitProject, class: button, icon: ui/exit.png, style: flatButton, mouseBorder: [10, 10, 10, 10] }
    fill: centre
    border: [-7, 0, 10, 0]

...